### ISSUE TITLE
SALT modules for TTP - reasoning

### ISSUE THREAD

**Issue by dmulyalin** [vmware-archive/salt-ext-ttp#1]
Hi,

If you do not mind, may I know what is the purpose of this repository?

Can see the ttp modules were copied from this pull request - https://github.com/saltstack/salt/pull/58754

However, lots of commits were added around them.

Hence decided to find out what are the reasons behind all this work.

**Comment by s0undt3ch** [comment]
Hello @dmulyalin.

This repository was indeed created based on your work on https://github.com/saltstack/salt/pull/58754. Credits maintained.

Salt, over the years, has accumulated a vast number of execution modules, state modules, etc.

Also for [quite some time](https://github.com/saltstack/salt/pull/31218), Salt supports 3rd-party packages to extend salt, but [until recently](https://github.com/saltstack/pytest-salt-factories) there was no **simple way** to test those 3rd-party packages.

I picked your pull request because it had more than one type of loader and it also included the required tests to do a PoC and discover where this process is not yet working(if at all), [create a tool that could simplify creating 3rd-party Salt extensions](https://github.com/salt-extensions/salt-extension) and see what needs to be documented.

With that said, please forgive me for not asking for permission, but I only wanted to ping you on the matter once I had this fully working.

**Comment by dmulyalin** [comment]
Thank you for response and explaining your intentions. Have no concerns about using TTP pull request for your work, its more about willing to know what are you trying to achieve.

If I understood it right, you needed some module not yet merged in SALT with several loaders and tests, and you picked up TTP pull request based on this criteria to use it as guinea pig in your PoC, again, having no issues with that, glad to help actually :)

That module of yours to support entry points via setup tools, was merged in SALT on 17 Feb 2016 and still [included](https://github.com/saltstack/salt/blob/da6819735ce055f16e326472cb1768faece72ad6/salt/loader.py#L152) in SALT, have not heard of it, but seems as a really nice feature, will give it a try.

**Comment by s0undt3ch** [comment]
Yeah, we never got to properly publicise the entry points feature of salt.
We're going to soon though :)
